name: Bot Saham Pro

on:
  schedule:
    # Jam 09:15 WIB (02:15 UTC) -> Untuk Sinyal Pembukaan
    - cron: '15 2 * * 1-5' 
    # Jam 16:30 WIB (09:30 UTC) -> Untuk Sinyal Penutupan
    - cron: '30 9 * * 1-5'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Jalankan Bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py
